AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.gemspec'
  DisplayCopNames: true
  StyleGuideCopsOnly: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'spec/**/*.rb'
